// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.Map;

public class GroupDeletionTests {
    private static WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        if (driver == null) {
            driver = new FirefoxDriver();
            driver.get("http://localhost/addressbook/");
            driver.manage().window().setSize(new Dimension(1750, 1226));
            driver.findElement(By.name("user")).sendKeys("admin");
            driver.findElement(By.name("pass")).sendKeys("secret");
            driver.findElement(By.xpath("//input[@value=\'Login\']")).click();
        }
    }

    @AfterEach
    public void tearDown() {
        driver.findElement(By.linkText("Logout")).click();
        driver.quit();
    }

    private boolean isElementPresent(By locator) {
        try {
            driver.findElement(locator);
            return true;
        } catch (NoSuchElementException e) {
            return false;
        }
    }

    @Test
    public void canDeleteAGroup() {
//        driver.get("http://localhost/addressbook/group.php");
        if (!isElementPresent(By.name("new"))) {
            driver.findElement(By.linkText("groups")).click();
        }
        if (!isElementPresent(By.name("selected[]"))) {
            driver.findElement(By.name("new")).click();
            driver.findElement(By.name("group_name")).click();
            driver.findElement(By.name("group_name")).sendKeys("new group1");
            driver.findElement(By.name("group_header")).sendKeys("group header1");
            driver.findElement(By.name("group_footer")).sendKeys("group footer1");
            driver.findElement(By.name("submit")).click();
            driver.findElement(By.linkText("group page")).click();
        }
//        driver.manage().window().setSize(new Dimension(1750, 1226));
//        driver.findElement(By.linkText("groups")).click();
//        driver.findElement(By.xpath("//div[@id=\'content\']/form/span/input")).click();
//            driver.findElement(By.xpath("//div[@id=\'content\']/form/span/input")).click();

//        driver.findElement(By.xpath("(//input[@name=\'delete\'])[2]")).click();
//        driver.findElement(By.name("selected[]")).click();
//        driver.findElement(By.name("delete")).click();
        driver.findElement(By.name("selected[]")).click();
        driver.findElement(By.name("delete")).click();
        driver.findElement(By.linkText("group page")).click();
    }
}
