// Generated by Selenium IDE

import model.GroupData;
import org.junit.jupiter.api.Test;

public class GroupDeletionTests extends TestBase {
    @Test
    public void canDeleteAGroup() {
        openGroupsPage();
        if (!isGroupPresent()) {
            createGroup(new GroupData("new group1", "name header1", "name footer1"));
        }
        removeAGroup();
    }
}
