// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;

public class GroupDeletionTests extends TestBase {

    @Test
    public void canDeleteAGroup() {
        openGroupsPage();
        if (!isGroupPresent()) {
            createGroup("new group1", "group header1", "group footer1");
        }
        removeAGroup();
    }
}
